apiVersion: v1
kind: Service
metadata:
  name: todo-list-srv
spec:
  type: NodePort
  selector:
    app: todo-serve
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 8080

